--------------------------------------------------------
--  File created - Tuesday-November-21-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE ACCOUNT 
   (	"ID" VARCHAR2(10 BYTE), 
	"F_NAME" VARCHAR2(20 BYTE), 
	"L_NAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(60 BYTE), 
	"CITY" VARCHAR2(15 BYTE), 
	"BRANCH" VARCHAR2(15 BYTE), 
	"ZIP" VARCHAR2(8 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ACCOUNT_TYPE" VARCHAR2(15 BYTE), 
	"REG_DATE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ACCOUNT
SET DEFINE OFF;
